### ISSUE TITLE
Lines on a points chart?

### ISSUE THREAD

**Issue by packetmonkey** [Fullscreen/squid#37]
Is it possible to overlay a line on a points chart? I want to graph out a scatter plot and then draw the averages along the horizontal and vertical axis.

I didn't see anything in the manual or docs for this, the `two_axis` type looks close but it paints a line over a bar chart instead of a scatter plot and I'm unsure how to change that if possible.

Sorry if this isn't the correct place to ask this question.

**Comment by claudiofullscreen** [comment]
Should the line graph and the point graph refer to the same series, or to two different series?

**Comment by packetmonkey** [comment]
I think they would be different series.

Given a plot of data containing

```ruby
data = { widgets: { 1 => 2, 2 => 4, 3 => 6, 4 => 8 } }
```
I would also want to draw a vertical line at 2.5 and a horizontal line at 5, so the lines are derived from the points but short of some ideal averages helper for the scatter plots, it makes sense to do that calculation and pass in the additional series I think.

Assuming I understand correctly :)

**Comment by claudiofullscreen** [comment]
I think you are suggesting two different features here.

1) A new `type: :scatter` graph that is similar to `type: :point` but include some average lines

2) A new option for `type: :two_axis` to be able to set _which_ types of graphs to combine (instead of only having line vs. column)

Is that correct? 

Regarding 2), I think that might be a good option, and I would accept a PR. Any suggestion on the name of the new option?

Regarding 1), adding types is also a good idea, but I would need a little more context about this new type… do you have any real-life examples I can look at?

Thanks!

**Comment by packetmonkey** [comment]
Sorry if I'm being unclear.

Let me give you a solid example of my use case and what I have vs what I am trying to work towards.

I have a database containing food items for a restaurant, their profitability and how many of them are sold.

```ruby
require 'prawn'
require 'squid'

Prawn::Document.generate 'out.pdf' do |pdf|
  data = {
    items: {
      20 => 1.99,
      35 => 2.29,
      15 => 4.99,
      55 => 0.59
    }
  }
  pdf.chart data, type: :point, labels: [false], formats: []
end
```

<img width="288" alt="screen shot 2015-09-15 at 5 03 41 pm" src="https://cloud.githubusercontent.com/assets/4451/9890076/cc580356-5bcb-11e5-9abb-3263b7890b83.png">

What I would like to do is take this existing graph and overlay vertical and horizontal lines at 31.25 and 2.465 so I would end up with something close to

<img width="288" alt="screen shot 2015-09-15 at 5 03 41 pm" src="https://cloud.githubusercontent.com/assets/4451/9890117/0c51ff52-5bcc-11e5-9100-c3408850f07b.png">

In terms of additional features, I would also like to overlay a specific text label with each point, and additional text in the four corners like


```ruby
# Not really executable, just possible API I made up on the fly

require 'prawn'
require 'squid'

Prawn::Document.generate 'out.pdf' do |pdf|
  data = {
    items: [
      { label: 'Hamburger', x: 20, y: 1.99 },
      { label: 'Cheeseburger', x: 35, y: 2.29 },
      { label: 'Chili Dog', x: 15, y: 4.99 },
      { label: 'Fries', x: 55, y: 0.59 }
    ]
  }
  pdf.chart data, type: :point, labels: [false], formats: []
end
```

<img width="288" alt="screen shot 2015-09-15 at 5 03 41 pm" src="https://cloud.githubusercontent.com/assets/4451/9890215/a04d6c5a-5bcc-11e5-8175-b1612da4498f.png">

I just realized I didn't sort the data set so the items as they are plotted are not in order, but hopefully my intention is clear.

Does this help explain what I am shooting for?

**Comment by claudiofullscreen** [comment]
Regarding the labels, if "Hamburger / Cheeseburger / Chili Dog and Fries" are your categories, why don't use those as the labels for the X axis?

In other words, wouldn't the following be ok?

```ruby
pdf.chart items: {"Hamburgers (20)" => 1.99, "Cheeseburger (35)" => 2.29, "Chili Dog (15)" => 4.99, "Fries (55)" => 0.59}, format: :currency
```

**Comment by packetmonkey** [comment]
Sorry for not getting back to you sooner.

Hamburger etc.. are my data points, models with extra attributes. Such as

```ruby
food_item1 = { name: 'Hamberger', sell_price: 4.99, number_sold: 150}
food_item2 = { name: 'Chili Dog', sell_price: 3.99, number_sold: 275 }
```

and then plot two points on a graph with the x-axis being the range of sell prices and the y-axis being the range of number sold, and want the label on the point to just be the name of the item.

**Comment by claudiofullscreen** [comment]
Hello again!

If I understand correctly, you do want a [scatter plot](https://en.wikipedia.org/wiki/Scatter_plot).

I don't think that's a graph that I can easily include in Squid. Same thing goes for pie chart.

Graphs in Squid are designed so that all the categories are equally distributed along the X axis. There is no concept of "items" that is separate from "categories on the X axis".

I believe that would require a lot of changes in the public API (and private code) of Squid.
I'm open to suggestions, but I don't plan on writing the code to add those graphs to Squid. :neutral_face:

**Comment by packetmonkey** [comment]
Fair enough! I really appreciate you talking though it with me. Squid is still a great library, I'll just need to wait for another chance to use it :)

Thanks again!
