### ISSUE TITLE
Support for y-axis and x-axis label

### ISSUE THREAD

**Issue by fxfilmxf** [Fullscreen/squid#40]
We should be able to add an x-axis label and y-axis label. [example](http://www.phplot.com/phplotdocs/images/labels-bar.png) where Independent Variable and Dependent Variable are the labels.

**Comment by claudiofullscreen** [comment]
Thanks for stopping by! :wave: 

Currently I am using the legend to display the "y-axis label", since it looks clearer in case you have multiple series.

Regarding the "x-axis label", you could try by simply prepending a `text` Prawn command to the `graph` command… that should write a label right below the graph. Let me know :ribbon:

**Comment by lbrito1** [comment]
Hi @claudiofullscreen , could you show how you use legends for the y axis label? I'm currently using Prawn rotate and `text` which is rather painful and hacky.
